-- Robinhood Stock Battlefield: additive generic market-pair foundation.
--
-- This migration deliberately preserves the legacy native-oriented columns used by
-- existing BNB/Robinhood readers while introducing explicit base/quote semantics.
-- Existing MEME/WETH Robinhood markets are backfilled as CANONICAL_NATIVE. Future
-- MEME/Stock Token graduations must register CANONICAL_STOCK rows explicitly.

create table if not exists public.market_pairs (
  id bigint generated by default as identity primary key,
  chain_id integer not null,
  campaign_address text not null,
  pool_address text not null,
  base_token_address text not null,
  quote_token_address text not null,
  base_decimals integer,
  quote_decimals integer,
  quote_asset_type text not null,
  market_role text not null,
  venue text not null,
  fee_tier integer,
  router_address text,
  factory_address text,
  verified boolean not null default false,
  trading_enabled boolean not null default false,
  indexing_enabled boolean not null default true,
  oracle_feed_address text,
  market_policy_version text,
  reserve_base_raw text,
  reserve_quote_raw text,
  last_verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_pairs_distinct_assets check(lower(base_token_address)<>lower(quote_token_address)),
  constraint market_pairs_quote_asset_type_valid check(
    quote_asset_type=any(array['WRAPPED_NATIVE','STOCK_TOKEN','OTHER']::text[])
  ),
  constraint market_pairs_market_role_valid check(
    market_role=any(array['CANONICAL_NATIVE','CANONICAL_STOCK','ADDITIONAL','EXTERNAL']::text[])
  ),
  constraint market_pairs_decimals_valid check(
    (base_decimals is null or base_decimals between 0 and 36)
    and (quote_decimals is null or quote_decimals between 0 and 36)
  ),
  constraint market_pairs_fee_tier_valid check(fee_tier is null or fee_tier between 0 and 1000000),
  constraint market_pairs_reserve_base_raw_valid check(reserve_base_raw is null or reserve_base_raw~'^[0-9]+$'),
  constraint market_pairs_reserve_quote_raw_valid check(reserve_quote_raw is null or reserve_quote_raw~'^[0-9]+$')
);

create unique index if not exists market_pairs_pool_uidx
  on public.market_pairs(chain_id,lower(pool_address));

create unique index if not exists market_pairs_canonical_campaign_uidx
  on public.market_pairs(chain_id,lower(campaign_address))
  where market_role in ('CANONICAL_NATIVE','CANONICAL_STOCK');

create index if not exists market_pairs_campaign_idx
  on public.market_pairs(chain_id,lower(campaign_address),updated_at desc);

create index if not exists market_pairs_quote_asset_idx
  on public.market_pairs(chain_id,lower(quote_token_address),quote_asset_type,trading_enabled,indexing_enabled);

comment on table public.market_pairs is
  'Pair-level market registry. Canonical lifecycle remains in campaign_market_state; this table defines explicit base/quote market semantics.';
comment on column public.market_pairs.quote_asset_type is
  'WRAPPED_NATIVE, STOCK_TOKEN, or OTHER. Never infer Stock Token identity from symbol alone.';
comment on column public.market_pairs.market_role is
  'V1 campaigns have one canonical market: CANONICAL_NATIVE or CANONICAL_STOCK.';

-- Normalize the existing dex_pools schema without removing compatibility columns.
alter table public.dex_pools
  add column if not exists base_token_address text,
  add column if not exists quote_token_address text,
  add column if not exists base_decimals integer,
  add column if not exists quote_decimals integer,
  add column if not exists quote_asset_type text,
  add column if not exists market_role text,
  add column if not exists reserve_base_raw text,
  add column if not exists reserve_quote_raw text,
  add column if not exists price_quote numeric,
  add column if not exists quote_volume_24h numeric,
  add column if not exists volume_usd_24h numeric,
  add column if not exists oracle_feed_address text,
  add column if not exists market_policy_version text;

-- Existing Robinhood V3 rows are the accepted direct MEME/WETH markets. We only
-- backfill chain 4663/46630 here; other chains keep their historical semantics.
update public.dex_pools
set base_token_address=coalesce(nullif(base_token_address,''),token_address),
    quote_token_address=coalesce(nullif(quote_token_address,''),wrapped_native_address),
    quote_asset_type=coalesce(nullif(quote_asset_type,''),'WRAPPED_NATIVE'),
    market_role=coalesce(nullif(market_role,''),'CANONICAL_NATIVE'),
    reserve_base_raw=coalesce(reserve_base_raw,reserve_token_raw),
    reserve_quote_raw=coalesce(reserve_quote_raw,reserve_native_raw)
where chain_id in (4663,46630);

alter table public.dex_pools drop constraint if exists dex_pools_quote_asset_type_valid;
alter table public.dex_pools add constraint dex_pools_quote_asset_type_valid check(
  quote_asset_type is null or quote_asset_type=any(array['WRAPPED_NATIVE','STOCK_TOKEN','OTHER']::text[])
);
alter table public.dex_pools drop constraint if exists dex_pools_market_role_valid;
alter table public.dex_pools add constraint dex_pools_market_role_valid check(
  market_role is null or market_role=any(array['CANONICAL_NATIVE','CANONICAL_STOCK','ADDITIONAL','EXTERNAL']::text[])
);
alter table public.dex_pools drop constraint if exists dex_pools_pair_decimals_valid;
alter table public.dex_pools add constraint dex_pools_pair_decimals_valid check(
  (base_decimals is null or base_decimals between 0 and 36)
  and (quote_decimals is null or quote_decimals between 0 and 36)
);

-- Normalize trades. Legacy native_amount_raw/price_bnb remain populated for
-- historical/native clients. Stock-market writers must write quote_* fields and
-- must not pretend a Stock Token amount is native ETH.
alter table public.dex_trades
  add column if not exists base_amount_raw text,
  add column if not exists quote_amount_raw text,
  add column if not exists base_amount numeric,
  add column if not exists quote_amount numeric,
  add column if not exists price_quote numeric,
  add column if not exists quote_asset_type text,
  add column if not exists quote_token_address text,
  add column if not exists volume_usd numeric,
  add column if not exists reference_price_usd numeric,
  add column if not exists reference_price_updated_at timestamptz;

update public.dex_trades t
set base_amount_raw=coalesce(t.base_amount_raw,t.token_amount_raw),
    quote_amount_raw=coalesce(t.quote_amount_raw,t.native_amount_raw),
    base_amount=coalesce(t.base_amount,t.token_amount),
    quote_amount=coalesce(t.quote_amount,t.native_amount),
    price_quote=coalesce(t.price_quote,t.price_bnb),
    quote_asset_type=coalesce(nullif(t.quote_asset_type,''),'WRAPPED_NATIVE'),
    quote_token_address=coalesce(
      nullif(t.quote_token_address,''),
      (select dp.wrapped_native_address
         from public.dex_pools dp
        where dp.chain_id=t.chain_id and lower(dp.pair_address)=lower(t.pair_address)
        limit 1)
    )
where t.chain_id in (4663,46630);

alter table public.dex_trades drop constraint if exists dex_trades_quote_asset_type_valid;
alter table public.dex_trades add constraint dex_trades_quote_asset_type_valid check(
  quote_asset_type is null or quote_asset_type=any(array['WRAPPED_NATIVE','STOCK_TOKEN','OTHER']::text[])
);
alter table public.dex_trades drop constraint if exists dex_trades_pair_raw_amounts_valid;
alter table public.dex_trades add constraint dex_trades_pair_raw_amounts_valid check(
  (base_amount_raw is null or base_amount_raw~'^[0-9]+$')
  and (quote_amount_raw is null or quote_amount_raw~'^[0-9]+$')
);

-- Backfill the pair registry from already accepted Robinhood direct-native pools.
insert into public.market_pairs(
  chain_id,campaign_address,pool_address,base_token_address,quote_token_address,
  base_decimals,quote_decimals,quote_asset_type,market_role,venue,fee_tier,
  router_address,factory_address,verified,trading_enabled,indexing_enabled,
  oracle_feed_address,market_policy_version,reserve_base_raw,reserve_quote_raw,
  last_verified_at,created_at,updated_at
)
select
  dp.chain_id,dp.campaign_address,dp.pair_address,
  coalesce(nullif(dp.base_token_address,''),dp.token_address),
  coalesce(nullif(dp.quote_token_address,''),dp.wrapped_native_address),
  dp.base_decimals,dp.quote_decimals,
  coalesce(nullif(dp.quote_asset_type,''),'WRAPPED_NATIVE'),
  coalesce(nullif(dp.market_role,''),'CANONICAL_NATIVE'),
  'robinhood_v3',
  case when dp.fee_bps is null then null else dp.fee_bps*100 end,
  dp.router_address,dp.factory_address,
  coalesce(cms.pool_verified,false),
  dp.support_enabled and dp.indexing_enabled and coalesce(cms.pool_verified,false),
  dp.indexing_enabled,
  dp.oracle_feed_address,
  coalesce(dp.market_policy_version,'robinhood_market_v1'),
  coalesce(dp.reserve_base_raw,dp.reserve_token_raw),
  coalesce(dp.reserve_quote_raw,dp.reserve_native_raw),
  cms.last_verified_at,
  dp.created_at,now()
from public.dex_pools dp
left join public.campaign_market_state cms
  on cms.chain_id=dp.chain_id and lower(cms.campaign_address)=lower(dp.campaign_address)
where dp.chain_id in (4663,46630)
on conflict(chain_id,lower(pool_address)) do nothing;

create or replace view public.robinhood_market_pairs_v
with(security_invoker=true)
as
select
  mp.id,
  mp.chain_id as "chainId",
  mp.campaign_address as "campaignAddress",
  mp.pool_address as "poolAddress",
  mp.base_token_address as "baseTokenAddress",
  mp.quote_token_address as "quoteTokenAddress",
  mp.base_decimals as "baseDecimals",
  mp.quote_decimals as "quoteDecimals",
  mp.quote_asset_type as "quoteAssetType",
  mp.market_role as "marketRole",
  mp.venue,
  mp.fee_tier as "feeTier",
  mp.router_address as "routerAddress",
  mp.factory_address as "factoryAddress",
  mp.verified,
  mp.trading_enabled as "tradingEnabled",
  mp.indexing_enabled as "indexingEnabled",
  mp.oracle_feed_address as "oracleFeedAddress",
  mp.market_policy_version as "marketPolicyVersion",
  mp.reserve_base_raw as "reserveBaseRaw",
  mp.reserve_quote_raw as "reserveQuoteRaw",
  mp.last_verified_at as "lastVerifiedAt",
  mp.updated_at as "updatedAt"
from public.market_pairs mp
where mp.chain_id in (4663,46630);

comment on view public.robinhood_market_pairs_v is
  'Robinhood pair registry with explicit base/quote roles. Legacy wrapped-native fields are compatibility-only.';
