import { normalizeAddress } from "../../server/http.js";
import { assertVerifiedProjectOwner, sanitizeProjectImportMetadataPatch } from "./projectImportSecurity.js";

export function normalizeProjectIdentity(chainId,tokenAddress){const id=Number(chainId);if(!Number.isSafeInteger(id)||![56,101].includes(id))throw Object.assign(new Error("Unsupported project import chain"),{code:"UNSUPPORTED_CHAIN"});const token=normalizeAddress(tokenAddress,id);if(!token)throw Object.assign(new Error("Invalid token address or mint"),{code:"INVALID_TOKEN"});return{chainId:id,tokenAddress:token};}
function normalizeWallet(walletAddress,chainId){const wallet=normalizeAddress(walletAddress,chainId);if(!wallet)throw Object.assign(new Error("Invalid wallet"),{code:"INVALID_WALLET"});return wallet;}
export function assertResolverIdentity(requested,resolved){const canonical=normalizeProjectIdentity(resolved?.chainId,resolved?.tokenAddress);if(canonical.chainId!==requested.chainId||canonical.tokenAddress!==requested.tokenAddress)throw Object.assign(new Error("Resolver returned a different project identity"),{code:"RESOLVER_IDENTITY_MISMATCH"});return canonical;}
export function publicProject(row){if(!row)return null;return{id:String(row.id),chainId:Number(row.chain_id),tokenAddress:String(row.token_address),name:row.name??null,symbol:row.symbol??null,decimals:row.decimals==null?null:Number(row.decimals),totalSupply:row.total_supply??null,imageUrl:row.image_url??null,description:row.description??null,website:row.website??null,xUrl:row.x_url??null,telegramUrl:row.telegram_url??null,ownershipStatus:String(row.ownership_status||"ownership_pending"),projectOwnerWallet:row.project_owner_wallet??null,ownershipVerifiedAt:row.ownership_verified_at??row.verified_at??null,manualClaimWallet:row.manual_claim_wallet??null,manualClaimRequestedAt:row.manual_claim_requested_at??null,metadataUpdatedAt:row.metadata_updated_at??null,arenaStatus:row.status??row.arena_status??null,createdAt:row.created_at??null,updatedAt:row.updated_at??null};}
export async function lookupProjectImport(pool,{chainId,tokenAddress}){const identity=normalizeProjectIdentity(chainId,tokenAddress);const r=await pool.query(`SELECT * FROM public.arena_token_imports WHERE chain_id=$1 AND token_address=$2 LIMIT 1`,[identity.chainId,identity.tokenAddress]);return r.rows?.[0]||null;}
export async function listUserProjectImports(pool,{chainId,walletAddress}){const id=Number(chainId);if(![56,101].includes(id))throw Object.assign(new Error("Unsupported project import chain"),{code:"UNSUPPORTED_CHAIN"});const wallet=normalizeWallet(walletAddress,id);const r=await pool.query(`SELECT * FROM public.arena_token_imports WHERE chain_id=$1 AND (imported_by_wallet=$2 OR project_owner_wallet=$2 OR manual_claim_wallet=$2) ORDER BY metadata_updated_at DESC, created_at DESC`,[id,wallet]);return r.rows||[];}
export async function createProjectImport(pool,{resolverResult,signedWallet}){const identity=normalizeProjectIdentity(resolverResult?.chainId,resolverResult?.tokenAddress);const signer=normalizeWallet(signedWallet,identity.chainId);const verified=Boolean(resolverResult?.signedWalletMatchesAuthority);const r=await pool.query(`INSERT INTO public.arena_token_imports (chain_id,token_address,owner_wallet,imported_by_wallet,project_owner_wallet,name,symbol,decimals,total_supply,ownership_status,verified_at,ownership_verified_at,metadata_updated_at) VALUES ($1,$2,'',$3,$4,$5,$6,$7,$8,$9,CASE WHEN $9='ownership_verified' THEN NOW() ELSE NULL END,CASE WHEN $9='ownership_verified' THEN NOW() ELSE NULL END,NOW()) ON CONFLICT (chain_id,token_address) DO NOTHING RETURNING *`,[identity.chainId,identity.tokenAddress,signer,verified?signer:null,resolverResult?.name??null,resolverResult?.symbol??null,Number.isFinite(Number(resolverResult?.decimals))?Number(resolverResult.decimals):null,resolverResult?.totalSupply==null?null:String(resolverResult.totalSupply),verified?"ownership_verified":"ownership_pending"]);if(r.rows?.[0])return{created:true,project:r.rows[0]};return{created:false,project:await lookupProjectImport(pool,identity)};}
export async function claimExistingProject(pool,{resolverResult,signedWallet}){const identity=normalizeProjectIdentity(resolverResult?.chainId,resolverResult?.tokenAddress);const signer=normalizeWallet(signedWallet,identity.chainId);if(!resolverResult?.signedWalletMatchesAuthority)throw Object.assign(new Error("Current authority proof does not match signed wallet"),{code:"OWNERSHIP_PROOF_REQUIRED"});const existing=await lookupProjectImport(pool,identity);if(!existing)throw Object.assign(new Error("Imported project not found"),{code:"PROJECT_NOT_FOUND"});if(existing.ownership_status==="ownership_suspended")throw Object.assign(new Error("Project ownership is suspended"),{code:"OWNERSHIP_SUSPENDED"});if(existing.ownership_status==="ownership_verified"){
  const current=normalizeAddress(existing.project_owner_wallet||"",identity.chainId);
  if(current===signer)return existing;
  throw Object.assign(new Error("A different verified project owner already controls this project"),{code:"OWNERSHIP_CONFLICT"});
}
const r=await pool.query(`UPDATE public.arena_token_imports SET project_owner_wallet=$3,ownership_status='ownership_verified',verified_at=NOW(),ownership_verified_at=NOW(),manual_claim_wallet=NULL,manual_claim_requested_at=NULL,manual_claim_note=NULL,metadata_updated_at=NOW(),updated_at=NOW() WHERE chain_id=$1 AND token_address=$2 AND ownership_status NOT IN ('ownership_verified','ownership_suspended') RETURNING *`,[identity.chainId,identity.tokenAddress,signer]);if(r.rows?.[0])return r.rows[0];const raced=await lookupProjectImport(pool,identity);if(raced?.ownership_status==="ownership_verified"&&normalizeAddress(raced.project_owner_wallet||"",identity.chainId)===signer)return raced;throw Object.assign(new Error("Project ownership changed during claim"),{code:"OWNERSHIP_CONFLICT"});}
export async function requestManualProjectClaim(pool,{chainId,tokenAddress,signedWallet,note=null}){const identity=normalizeProjectIdentity(chainId,tokenAddress),signer=normalizeWallet(signedWallet,identity.chainId);const existing=await lookupProjectImport(pool,identity);if(!existing)throw Object.assign(new Error("Imported project not found"),{code:"PROJECT_NOT_FOUND"});if(existing.ownership_status==="ownership_verified")throw Object.assign(new Error("Manual claim cannot overwrite a verified owner"),{code:"OWNERSHIP_CONFLICT"});if(existing.ownership_status==="ownership_suspended")throw Object.assign(new Error("Project ownership is suspended"),{code:"OWNERSHIP_SUSPENDED"});const r=await pool.query(`UPDATE public.arena_token_imports SET manual_claim_wallet=$3,manual_claim_requested_at=NOW(),manual_claim_note=$4,ownership_status='ownership_manual_review',metadata_updated_at=NOW(),updated_at=NOW() WHERE chain_id=$1 AND token_address=$2 AND ownership_status NOT IN ('ownership_verified','ownership_suspended') RETURNING *`,[identity.chainId,identity.tokenAddress,signer,note==null?null:String(note).slice(0,1000)]);if(r.rows?.[0])return r.rows[0];throw Object.assign(new Error("Manual ownership review is not available for this project state"),{code:"MANUAL_CLAIM_NOT_ALLOWED"});}
export async function patchProjectMetadata(pool,{chainId,tokenAddress,signedWallet,patch}){const identity=normalizeProjectIdentity(chainId,tokenAddress),signer=normalizeWallet(signedWallet,identity.chainId);const safe=sanitizeProjectImportMetadataPatch(patch);if(Object.keys(safe).length===0)throw Object.assign(new Error("No mutable metadata fields supplied"),{code:"NO_METADATA_FIELDS"});const existing=await lookupProjectImport(pool,identity);assertVerifiedProjectOwner(existing,{wallet:signer,chainId:identity.chainId,token:identity.tokenAddress});const values={};for(const[k,v]of Object.entries(safe))values[k]=v==null||String(v).trim()===""?null:String(v).trim().slice(0,2048);const r=await pool.query(`UPDATE public.arena_token_imports SET description=CASE WHEN $4::boolean THEN $5 ELSE description END,website=CASE WHEN $6::boolean THEN $7 ELSE website END,x_url=CASE WHEN $8::boolean THEN $9 ELSE x_url END,telegram_url=CASE WHEN $10::boolean THEN $11 ELSE telegram_url END,metadata_updated_at=NOW(),updated_at=NOW() WHERE chain_id=$1 AND token_address=$2 AND project_owner_wallet=$3 AND ownership_status='ownership_verified' RETURNING *`,[identity.chainId,identity.tokenAddress,signer,Object.hasOwn(values,"description"),values.description??null,Object.hasOwn(values,"website"),values.website??null,Object.hasOwn(values,"x_url"),values.x_url??null,Object.hasOwn(values,"telegram_url"),values.telegram_url??null]);if(r.rows?.[0])return r.rows[0];throw Object.assign(new Error("Verified project owner required"),{code:"PROJECT_OWNER_REQUIRED"});}
export async function persistProjectImage(pool,{chainId,tokenAddress,signedWallet,imageUrl}){const identity=normalizeProjectIdentity(chainId,tokenAddress),signer=normalizeWallet(signedWallet,identity.chainId);const existing=await lookupProjectImport(pool,identity);assertVerifiedProjectOwner(existing,{wallet:signer,chainId:identity.chainId,token:identity.tokenAddress});const r=await pool.query(`UPDATE public.arena_token_imports SET image_url=$4,metadata_updated_at=NOW(),updated_at=NOW() WHERE chain_id=$1 AND token_address=$2 AND project_owner_wallet=$3 AND ownership_status='ownership_verified' RETURNING *`,[identity.chainId,identity.tokenAddress,signer,String(imageUrl||"")]);if(r.rows?.[0])return r.rows[0];throw Object.assign(new Error("Verified project owner required"),{code:"PROJECT_OWNER_REQUIRED"});}
