export const ANALYTICS_APPS = new Set(["public", "admin"]);

export const CATALOG_EVENT_NAMES = new Set([
  "$pageview",
  "$pageleave",
  "$identify",
  "$heartbeat",
  "$web_vital",
  "$function",
  "wallet_connect_started",
  "wallet_connect_succeeded",
  "wallet_connect_failed",
  "page_cta_clicked",
  "token_page_viewed",
  "token_create_started",
  "token_create_succeeded",
  "token_create_failed",
  "draft_created_started",
  "draft_created_succeeded",
  "draft_created_failed",
  "buy_started",
  "buy_submitted",
  "buy_failed",
  "sell_started",
  "sell_submitted",
  "sell_failed",
  "graduation_viewed",
  "recruiter_link_landed",
  "sponsorship_apply_started",
  "sponsorship_apply_submitted",
  "sponsorship_apply_failed",
  "reward_claim_started",
  "reward_claim_succeeded",
  "reward_claim_failed",
  "admin_signed_in",
  "admin_sign_in_failed",
  "admin_note_added",
  "admin_sponsorship_status_changed",
  "admin_promotor_refreshed",
  "admin_recruiter_updated",
]);

export const MAX_BATCH = 50;
export const MAX_PROPERTY_KEYS = 16;
export const MAX_STRING = 256;
