/**
 * The gen-7 airdrop pot in the gen-7 release tooling (founder, 2026-10-08: two airdrop pots per EVM chain, the
 * gen-6 "main" one and a "gen7" one, everything automated; docs/claude/payouts-and-rewards.md "two pots").
 *
 * The gen-7 TreasuryRouterV4 has its own CommunityRewardsVault (one router per vault), so the gen-7 pot needs its
 * own airdrop RewardDistributor: `batchOperator` is a single address and `createBatch` is onlyOwnerOrBatchOperator,
 * so one distributor serves one vault (the gen-7 HOLDER distributor's operator is the CreatorRewardsVaultV2, so it
 * cannot be reused either).
 *
 * Deploy (deployer): `new RewardDistributor(initialOwner = admin)`; the admin is the Safe on 56/4663, the deployer
 * on 97/46630.
 * Admin calls (generated by scripts/make-airdrop-setup-calls.mjs, imported, so the batch ids are the runner's own
 * weeklyContractBatchId(chainId, epochId, program, "gen7")):
 *   CommunityRewardsVault(gen-7).setRewardDistributor(gen-7 airdrop distributor)
 *   CommunityRewardsVault(gen-7).setAirdropOperator(operator)   -- the main vault's airdropOperator(), read on chain
 *   RewardDistributor(gen-7 airdrop).setBatchOperator(gen-7 CommunityRewardsVault)
 *   RewardDistributor(gen-7 airdrop).authorizeBatch(id, cap, weekEnd, weekEnd + 6 d) x 12 weeks x {trader, creator}
 * Cap per batch: the main pot's current authorization (the main distributor's latest batchAuthorization.maxAmount
 * on chain, else the last authorizeBatch on that distributor in the repo's Safe batches), GEN7_AIRDROP_CAP
 * (native units, e.g. "5") overrides. GEN7_AIRDROP_OPERATOR overrides the operator.
 *
 * Every planner here returns only the calls chain state still lacks, so a rebuilt batch never repeats a done call.
 *
 * `runGen7AirdropWeek` rehearses one weekly draw of the gen-7 pot on a fork with the runner's own modules:
 * potRun.runPot (draw, materialize, fund, claim-open) over a fake DB client, chain.mjs resolvePoolWei and
 * ensureOnChainBatch against the fork. With no operator key in the environment the runner funds through its
 * funding-executor request (REWARD_FUNDING_EXECUTOR_URL); here that executor is local and sends
 * CommunityRewardsVault.fundAirdropBatch from the signer the caller passes (the impersonated airdrop operator on a
 * fork). chain.mjs reads the chain over HTTP, so a local JSON-RPC proxy forwards its calls to hardhat's provider
 * (works for anvil forks and the in-process hardhat fork alike).
 */
import crypto from "node:crypto";
import fs from "node:fs";
import http from "node:http";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { ethers, network } from "hardhat";
import type { PlannedCall } from "./safeCallPlan";

const ROOT = path.resolve(__dirname, "..", "..");
const esm = (rel: string): Promise<any> => Function("s", "return import(s)")(pathToFileURL(path.join(ROOT, rel)).href);

export const GEN7_POT = "gen7";
export const GEN7_AIRDROP_WEEKS = 12;
export const AIRDROP_PROGRAMS = ["airdrop_trader", "airdrop_creator"] as const;
const DAY = 86_400;
const WEEK = 7 * DAY;

export const COMMUNITY_VAULT_ABI = [
  "function admin() view returns (address)",
  "function router() view returns (address)",
  "function rewardDistributor() view returns (address)",
  "function airdropOperator() view returns (address)",
  "function warzoneAirdropBalance() view returns (uint256)",
  "function fundAirdropBatch(bytes32 batchId, bytes32 merkleRoot, uint64 claimDeadline, uint256 amount)",
];
export const DISTRIBUTOR_ABI = [
  "function owner() view returns (address)",
  "function batchOperator() view returns (address)",
  "function batchAuthorization(bytes32) view returns (uint256 maxAmount, uint64 publishAfter, uint64 publishDeadline, bool authorized, bool consumed)",
  "function batches(bytes32) view returns (bytes32 merkleRoot, uint256 totalFunded, uint256 totalClaimed, uint64 claimDeadline, bool paused, bool exists)",
  "function totalOutstandingRewards() view returns (uint256)",
  "function claim(bytes32 batchId, uint256 amount, bytes32[] proof)",
  "function hasClaimed(bytes32, address) view returns (bool)",
  "function authorizeBatch(bytes32 batchId, uint256 maxAmount, uint64 publishAfter, uint64 publishDeadline)",
];

const same = (a: string, b: string) => ethers.getAddress(a) === ethers.getAddress(b);
const isZero = (a: string | null | undefined) => !a || a === ethers.ZeroAddress;

/** The env lines the API + weekly runner need once the gen-7 pot is wired (both or neither, pots.mjs). */
export function gen7AirdropEnvLines(chainId: number, vault: string, distributor: string): string[] {
  return [`COMMUNITY_REWARDS_VAULT_ADDRESS_GEN7_${chainId}=${ethers.getAddress(vault)}`, `REWARD_DISTRIBUTOR_ADDRESS_GEN7_${chainId}=${ethers.getAddress(distributor)}`];
}

export function printGen7AirdropEnv(chainId: number, vault: string, distributor: string, log: (l: string) => void = console.log) {
  log(`gen-7 airdrop pot: set on the API + weekly airdrop job AFTER the batch that wires it is executed (both or neither):`);
  for (const line of gen7AirdropEnvLines(chainId, vault, distributor)) log(`    ${line}`);
}

/** Deploys the gen-7 airdrop RewardDistributor (owner = admin) and reads the owner back. */
export async function deployGen7AirdropDistributor(deployer: any, admin: string): Promise<{ address: string; block: number }> {
  const dist = await (await ethers.getContractFactory("RewardDistributor", deployer)).deploy(admin);
  await dist.waitForDeployment();
  const address = ethers.getAddress(await dist.getAddress());
  const owner = await new ethers.Contract(address, DISTRIBUTOR_ABI, ethers.provider).owner();
  if (!same(owner, admin)) throw new Error(`gen-7 airdrop distributor ${address} owner ${owner} != ${admin}`);
  const block = Number((await dist.deploymentTransaction()?.wait())?.blockNumber ?? 0);
  return { address, block };
}

/** The main pot of a chain: the live router's CommunityRewardsVault, its distributor and airdrop operator. */
export async function readMainAirdropPot(mainVault: string) {
  const v = new ethers.Contract(mainVault, COMMUNITY_VAULT_ABI, ethers.provider);
  const [distributor, operator] = await Promise.all([v.rewardDistributor(), v.airdropOperator()]);
  return {
    vault: ethers.getAddress(mainVault),
    distributor: isZero(distributor) ? null : ethers.getAddress(distributor),
    operator: isZero(operator) ? null : ethers.getAddress(operator),
  };
}

function utcEpochEnd(nowSec: number): number {
  // epochWindow(): the Monday 00:00 UTC that ends the last full week (<= now).
  const d = new Date(nowSec * 1000);
  const day = d.getUTCDay();
  d.setUTCDate(d.getUTCDate() + (day === 0 ? -6 : 1 - day));
  d.setUTCHours(0, 0, 0, 0);
  return Math.floor(d.getTime() / 1000);
}
const epochIdForEnd = (endSec: number) => new Date((endSec - WEEK) * 1000).toISOString().slice(0, 10);

/** The main pot's per-batch cap, as the Safe authorizes it today. */
export async function mainAirdropCap(opts: { chainId: number; mainDistributor: string | null; recordChainIds?: number[] }): Promise<{ cap: bigint; source: string }> {
  const env = String(process.env.GEN7_AIRDROP_CAP || "").trim();
  if (env) {
    const cap = ethers.parseEther(env);
    if (cap <= 0n) throw new Error("GEN7_AIRDROP_CAP must be positive");
    return { cap, source: `env GEN7_AIRDROP_CAP=${env}` };
  }
  const { weeklyContractBatchId } = await esm("frontend/scripts/weekly-airdrop/materialize.mjs");
  const nowSec = Number((await ethers.provider.getBlock("latest"))!.timestamp);
  if (opts.mainDistributor) {
    const d = distAt(opts.mainDistributor);
    // Latest authorized main-pot week: scan from 8 weeks back to 26 ahead, keep the last one found.
    let found: { cap: bigint; epochId: string } | null = null;
    const end0 = utcEpochEnd(nowSec);
    for (let w = -8; w <= 26; w++) {
      const epochId = epochIdForEnd(end0 + w * WEEK);
      for (const program of AIRDROP_PROGRAMS) {
        const a = await d.batchAuthorization(weeklyContractBatchId(opts.chainId, epochId, program));
        if (a.authorized || a.consumed) found = { cap: BigInt(a.maxAmount), epochId };
      }
    }
    if (found && found.cap > 0n) return { cap: found.cap, source: `main distributor ${opts.mainDistributor} batchAuthorization(${found.epochId}).maxAmount on chain ${opts.chainId}` };
  }
  // Records: the last authorizeBatch in the repo's Safe batches on the main distributor (or, for a testnet whose
  // main pot was never authorized, on the mainnet main distributor it mirrors).
  const dirs: Record<number, string> = { 56: "bnb", 4663: "robinhood", 97: "bscTestnet", 46630: "robinhood" };
  for (const chainId of opts.recordChainIds ?? [opts.chainId]) {
    const dir = path.join(ROOT, "deployments", dirs[chainId] || "");
    if (!fs.existsSync(dir)) continue;
    let last: { cap: bigint; file: string; publishAfter: bigint } | null = null;
    for (const f of fs.readdirSync(dir).filter((n) => n.endsWith(".safe-batch.json"))) {
      const batch = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
      if (Number(batch.chainId) !== chainId) continue;
      const mainDistributor = chainId === opts.chainId ? opts.mainDistributor : null;
      for (const tx of batch.transactions || []) {
        if (tx.contractMethod?.name !== "authorizeBatch") continue;
        if (mainDistributor && !same(tx.to, mainDistributor)) continue;
        const v = tx.contractInputsValues || {};
        const id = String(v.batchId || "");
        const epochId = new Date((Number(v.publishAfter) - WEEK) * 1000).toISOString().slice(0, 10);
        const isAirdropId = AIRDROP_PROGRAMS.some((p) => weeklyContractBatchId(chainId, epochId, p) === id);
        if (!isAirdropId) continue;
        if (!last || BigInt(v.publishAfter) >= last.publishAfter) last = { cap: BigInt(v.maxAmount), file: f, publishAfter: BigInt(v.publishAfter) };
      }
    }
    if (last && last.cap > 0n) return { cap: last.cap, source: `deployments/${dirs[chainId]}/${last.file} (last main-pot authorizeBatch on chain ${chainId})` };
  }
  throw new Error(`no main-pot airdrop authorization found for chain ${opts.chainId}; set GEN7_AIRDROP_CAP (native units)`);
}

function distAt(address: string) {
  return new ethers.Contract(address, DISTRIBUTOR_ABI, ethers.provider);
}

export type Gen7AirdropSetup = {
  distributor: string;
  mainVault: string;
  mainDistributor: string | null;
  operator: string;
  operatorSource: string;
  cap: string;
  capSource: string;
  weeks: number;
};

/**
 * Operator + cap for the gen-7 pot, read from the main pot. Mainnet refuses a main vault without an airdrop
 * operator (the runner key would have nothing to fund with); a testnet falls back to its admin (the deployer).
 */
export async function resolveGen7AirdropSetup(opts: { chainId: number; mainVault: string; distributor: string; testnetAdmin?: string }): Promise<Gen7AirdropSetup> {
  const main = await readMainAirdropPot(opts.mainVault);
  const envOp = String(process.env.GEN7_AIRDROP_OPERATOR || "").trim();
  let operator: string;
  let operatorSource: string;
  if (envOp) {
    operator = ethers.getAddress(envOp);
    operatorSource = "env GEN7_AIRDROP_OPERATOR";
  } else if (main.operator) {
    operator = main.operator;
    operatorSource = `main vault ${main.vault}.airdropOperator()`;
  } else if (opts.testnetAdmin) {
    operator = ethers.getAddress(opts.testnetAdmin);
    operatorSource = `testnet: main vault ${main.vault} has no airdropOperator; the admin (deployer)`;
  } else {
    throw new Error(`main CommunityRewardsVault ${main.vault} has no airdropOperator on chain ${opts.chainId}; set GEN7_AIRDROP_OPERATOR or wire the main pot first`);
  }
  const mirror: Record<number, number> = { 97: 56, 46630: 4663 };
  const { cap, source } = await mainAirdropCap({ chainId: opts.chainId, mainDistributor: main.distributor, recordChainIds: mirror[opts.chainId] ? [opts.chainId, mirror[opts.chainId]] : [opts.chainId] });
  return { distributor: ethers.getAddress(opts.distributor), mainVault: main.vault, mainDistributor: main.distributor, operator, operatorSource, cap: cap.toString(), capSource: source, weeks: GEN7_AIRDROP_WEEKS };
}

/**
 * The gen-7 pot's wiring + pre-authorization calls that chain state still lacks, in the setup script's order
 * (wiring, then the authorizations week by week). Generated by make-airdrop-setup-calls.mjs (`--wiring gen7
 * --only gen7`) at the current block time.
 */
export async function planGen7AirdropCalls(opts: { chainId: number; vault: string; setup: Gen7AirdropSetup }): Promise<PlannedCall[]> {
  const { airdropSetupCalls } = await esm("scripts/make-airdrop-setup-calls.mjs");
  const nowSec = Number((await ethers.provider.getBlock("latest"))!.timestamp);
  const all: any[] = airdropSetupCalls({
    chainId: opts.chainId,
    weeks: opts.setup.weeks,
    now: new Date(nowSec * 1000),
    pots: [{ pot: GEN7_POT, vault: opts.vault, distributor: opts.setup.distributor, cap: BigInt(opts.setup.cap), operator: opts.setup.operator, wire: true }],
  });
  const vault = new ethers.Contract(opts.vault, COMMUNITY_VAULT_ABI, ethers.provider);
  const dist = distAt(opts.setup.distributor);
  const out: PlannedCall[] = [];
  for (const c of all) {
    if (c.fn === "setRewardDistributor" && same(await vault.rewardDistributor(), c.args[0])) continue;
    if (c.fn === "setAirdropOperator" && same(await vault.airdropOperator(), c.args[0])) continue;
    if (c.fn === "setBatchOperator" && same(await dist.batchOperator(), c.args[0])) continue;
    if (c.fn === "authorizeBatch") {
      const a = await dist.batchAuthorization(c.args[0]);
      if (a.authorized || a.consumed) continue;
    }
    out.push({ contract: c.contract, to: c.to, fn: c.fn, args: c.args, note: c.note ?? (c.fn === "setAirdropOperator" ? `= the main pot's operator (${opts.setup.operatorSource})` : "gen-7 airdrop pot") });
  }
  return out;
}

/** Read-back of the gen-7 pot after its batch: wiring and the authorized weeks (runner's own runway check). */
export async function readGen7AirdropPot(opts: { chainId: number; vault: string; setup: Gen7AirdropSetup; admin: string }) {
  const vault = new ethers.Contract(opts.vault, COMMUNITY_VAULT_ABI, ethers.provider);
  const dist = distAt(opts.setup.distributor);
  const [rd, op, bo, owner, vAdmin] = await Promise.all([vault.rewardDistributor(), vault.airdropOperator(), dist.batchOperator(), dist.owner(), vault.admin()]);
  const wired = same(rd, opts.setup.distributor) && same(op, opts.setup.operator) && same(bo, opts.vault) && same(owner, opts.admin) && same(vAdmin, opts.admin);
  return { wired, rewardDistributor: rd, airdropOperator: op, batchOperator: bo, owner };
}

/**
 * The runner's runway check (authorizationHorizon.mjs checkAirdropRunway, dry run: logs only) for the given pots,
 * as the runner sees it at `nowSec` (its draw week is the one that ended on the last Monday).
 */
export async function runnerRunway(opts: { chainId: number; pots: Array<{ pot: string; distributorAddress: string }>; nowSec: number }) {
  const horizon = await esm("frontend/scripts/weekly-airdrop/authorizationHorizon.mjs");
  const chain = await esm("frontend/scripts/weekly-airdrop/chain.mjs");
  const currentEnd = new Date(utcEpochEnd(opts.nowSec) * 1000);
  const quiet = { log: (l: string) => console.log(`[airdrop-runway] ${l}`), error: (l: string) => console.log(`[airdrop-runway] ${l}`) };
  return withRunnerEnv(opts.chainId, {}, async () => ({ ok: false, error: "no funding in a runway check" }), () =>
    horizon.checkAirdropRunway(fakeClient().client, { chainId: opts.chainId, pots: opts.pots, currentEnd, writeAlert: async () => {}, providerFor: chain.providerFor, dryRun: true, now: new Date(opts.nowSec * 1000), log: quiet }));
}

/** The first week end (Monday 00:00 UTC, >= the last ended one) whose gen-7 trader + creator ids are authorized. */
export async function firstAuthorizedGen7WeekEnd(chainId: number, distributor: string, nowSec: number): Promise<number | null> {
  const { weeklyContractBatchId } = await esm("frontend/scripts/weekly-airdrop/materialize.mjs");
  const d = distAt(distributor);
  const end0 = utcEpochEnd(nowSec);
  for (let w = 0; w <= 26; w++) {
    const end = end0 + w * WEEK;
    let ok = true;
    for (const p of AIRDROP_PROGRAMS) {
      const a = await d.batchAuthorization(weeklyContractBatchId(chainId, epochIdForEnd(end), p, GEN7_POT));
      if (!a.authorized || a.consumed) ok = false;
    }
    if (ok) return end;
  }
  return null;
}

/** A minimal pg-client stand-in: remembers the rows the runner writes, returns them where it reads them back. */
function fakeClient() {
  const batches = new Map<string, any>();
  const ledger: any[] = [];
  const queries: string[] = [];
  const client = {
    async query(sql: string, params: any[] = []) {
      const s = String(sql).replace(/\s+/g, " ").trim();
      queries.push(s.slice(0, 80));
      if (/^insert into public\.reward_batches/i.test(s)) {
        const row = { id: crypto.randomUUID(), status: "funding_check", total_amount: params[1], metadata: JSON.parse(params[3]) };
        batches.set(row.id, row);
        return { rows: [row] };
      }
      if (/^update public\.reward_batches set metadata=coalesce\(metadata,'\{\}'::jsonb\)\|\|\$2::jsonb,updated_at=now\(\) where id=\$1::uuid returning \*/i.test(s)) {
        const row = batches.get(params[0]);
        row.metadata = { ...row.metadata, ...JSON.parse(params[1]) };
        return { rows: [row] };
      }
      if (/^update public\.reward_batches set status='claim_open'/i.test(s)) {
        const row = batches.get(params[0]);
        row.status = "claim_open";
        row.metadata = { ...row.metadata, ...JSON.parse(params[2]) };
        return { rows: [row] };
      }
      if (/^insert into public\.reward_ledger/i.test(s)) {
        const row = { id: crypto.randomUUID(), source_id: params[0], wallet_address: params[1], amount: params[3], metadata: JSON.parse(params[4]) };
        ledger.push(row);
        return { rows: [row] };
      }
      return { rows: [] };
    },
  };
  return { client, batches, ledger, queries };
}

/**
 * A local HTTP server: `/rpc` forwards JSON-RPC to hardhat's provider (so chain.mjs's JsonRpcProvider reads the
 * fork), `/fund` is the funding executor the runner calls when no operator key is set.
 */
async function startLocalBridge(onFund: (payload: any) => Promise<any>) {
  const server = http.createServer((req, res) => {
    let body = "";
    req.on("data", (c) => (body += c));
    req.on("end", async () => {
      const reply = (code: number, obj: unknown) => {
        res.writeHead(code, { "content-type": "application/json" });
        res.end(JSON.stringify(obj, (_k, v) => (typeof v === "bigint" ? v.toString() : v)));
      };
      try {
        const parsed = JSON.parse(body || "{}");
        if (req.url === "/fund") return reply(200, await onFund(parsed));
        const one = async (r: any) => {
          try {
            return { jsonrpc: "2.0", id: r.id, result: await network.provider.send(r.method, r.params || []) };
          } catch (e: any) {
            return { jsonrpc: "2.0", id: r.id, error: { code: -32000, message: String(e?.message || e), data: e?.data } };
          }
        };
        reply(200, Array.isArray(parsed) ? await Promise.all(parsed.map(one)) : await one(parsed));
      } catch (e: any) {
        reply(500, { ok: false, error: String(e?.message || e) });
      }
    });
  });
  await new Promise<void>((r) => server.listen(0, "127.0.0.1", () => r()));
  const port = (server.address() as any).port;
  return { url: `http://127.0.0.1:${port}`, close: () => new Promise<void>((r) => server.close(() => r())) };
}

/** Runs `fn` with chain.mjs pointed at the fork through the local bridge (env restored afterwards). */
export async function withRunnerEnv<T>(chainId: number, extra: Record<string, string | undefined>, onFund: (payload: any) => Promise<any>, fn: (bridgeUrl: string) => Promise<T>): Promise<T> {
  const bridge = await startLocalBridge(onFund);
  const keys = [`BSC_RPC_HTTP_${chainId}`, "BSC_RPC_HTTP", "RPC_URL", `AIRDROP_OPERATOR_PRIVATE_KEY_${chainId}`, `AIRDROP_OPERATOR_PRIVATE_KEY_GEN7_${chainId}`, "REWARD_FUNDING_EXECUTOR_URL", "REWARD_FUNDING_EXECUTOR_TOKEN", "AIRDROP_ALLOW_CROSS_PROGRAM_WINNERS", "AIRDROP_TRADER_WINNERS", "AIRDROP_CREATOR_WINNERS", "AIRDROP_MAX_WINNERS_PER_PROGRAM", "AIRDROP_TARGET_PAYOUT_WEI", "AIRDROP_AUTH_ALERT_WEEKS", ...Object.keys(extra)];
  const saved = Object.fromEntries(keys.map((k) => [k, process.env[k]]));
  for (const k of keys) delete process.env[k];
  Object.assign(process.env, { [`BSC_RPC_HTTP_${chainId}`]: `${bridge.url}/rpc`, REWARD_FUNDING_EXECUTOR_URL: `${bridge.url}/fund`, REWARD_FUNDING_EXECUTOR_TOKEN: "local-rehearsal" });
  for (const [k, v] of Object.entries(extra)) if (v !== undefined) process.env[k] = v;
  try {
    return await fn(bridge.url);
  } finally {
    for (const [k, v] of Object.entries(saved)) {
      if (v === undefined) delete process.env[k];
      else process.env[k] = v;
    }
    await bridge.close();
  }
}

export type Gen7AirdropWeekResult = {
  epochId: string;
  vaultBefore: bigint;
  vaultAfter: bigint;
  distributionBps: number;
  batches: Array<{ program: string; contractBatchId: string; expectedId: string; merkleRoot: string; total: bigint; winners: Array<{ wallet: string; amount: bigint; proof: string[] }>; onChain: { totalFunded: bigint; exists: boolean; claimDeadline: bigint }; mainHasIt: boolean; status: string }>;
  fundRequests: any[];
  fundTxs: string[];
  alerts: any[];
  funded: bigint;
  main: { before: { vault: bigint; distBalance: bigint; outstanding: bigint }; after: { vault: bigint; distBalance: bigint; outstanding: bigint } };
};

/**
 * One weekly gen-7 draw on the fork through potRun.runPot: the week that ended on the last Monday (call it after
 * that Monday's 00:00 UTC, inside the authorized publish window), traders and creators given by the caller (the
 * rehearsal's own trading wallets stand in for the DB's candidate query), funded from the gen-7 vault by `fundAs`.
 */
export async function runGen7AirdropWeek(opts: {
  chainId: number;
  vault: string;
  distributor: string;
  mainVault: string;
  mainDistributor: string | null;
  traders: string[];
  creators: string[];
  fundAs: any;
  nativeUsd: number;
  distributionBps?: number;
}): Promise<Gen7AirdropWeekResult> {
  const potRun = await esm("frontend/scripts/weekly-airdrop/potRun.mjs");
  const config = await esm("frontend/scripts/weekly-airdrop/config.mjs");
  const { weeklyContractBatchId } = await esm("frontend/scripts/weekly-airdrop/materialize.mjs");
  const nowSec = Number((await ethers.provider.getBlock("latest"))!.timestamp);
  const { start, end, epochId } = config.epochWindow(new Date(nowSec * 1000));
  const claimDeadline = Math.floor(end.getTime() / 1000) + 7 * DAY; // AIRDROP_CLAIM_WINDOW_DAYS default 7
  const drawSecret = crypto.randomBytes(32).toString("hex");
  const distributionBps = opts.distributionBps ?? 5000;
  const vault = new ethers.Contract(opts.vault, COMMUNITY_VAULT_ABI, ethers.provider);
  const readMain = async () => ({
    vault: BigInt(await new ethers.Contract(opts.mainVault, COMMUNITY_VAULT_ABI, ethers.provider).warzoneAirdropBalance()),
    distBalance: opts.mainDistributor ? await ethers.provider.getBalance(opts.mainDistributor) : 0n,
    outstanding: opts.mainDistributor ? BigInt(await distAt(opts.mainDistributor).totalOutstandingRewards()) : 0n,
  });
  const mainBefore = await readMain();
  const vaultBefore = BigInt(await vault.warzoneAirdropBalance());
  const fundRequests: any[] = [];
  const fundTxs: string[] = [];
  const alerts: any[] = [];
  const fake = fakeClient();

  const onFund = async (payload: any) => {
    fundRequests.push(payload);
    if (payload.action !== "fund_airdrop_batch" || payload.functionName !== "fundAirdropBatch" || !same(payload.targetContract, opts.vault) || Number(payload.chainId) !== opts.chainId || !same(payload.distributorAddress, opts.distributor)) {
      return { ok: false, error: "unexpected funding request" };
    }
    const [batchId, root, deadline, amount] = payload.args;
    const tx = await (vault.connect(opts.fundAs) as any).fundAirdropBatch(batchId, root, BigInt(deadline), BigInt(amount));
    const rc = await tx.wait();
    fundTxs.push(tx.hash);
    return { ok: true, txHash: tx.hash, blockNumber: rc.blockNumber, requestId: `local-${fundTxs.length}` };
  };

  const toCandidate = (w: string, i: number) => ({ walletAddress: ethers.getAddress(w), finalWeight: 1 + i * 0.1, activityScore: 1, reasonCodes: ["rehearsal"], totalVolumeRaw: "0", countedVolumeRaw: "0" });
  await withRunnerEnv(opts.chainId, { [`AIRDROP_NATIVE_USD_${opts.chainId}`]: String(opts.nativeUsd) }, onFund, async () => {
    const ctx = { chainId: opts.chainId, epochId, start, end, claimDeadline, commitment: config.seedCommitment(drawSecret, opts.chainId, epochId), drawSecret, dryRun: false, distributionBps };
    await potRun.runPot(fake.client, ctx, { pot: GEN7_POT, label: "gen-7 pot", vaultAddress: ethers.getAddress(opts.vault), distributorAddress: ethers.getAddress(opts.distributor) }, new Set(), {
      // The DB-only steps (the rest is the runner's own code against the fork).
      findEpochBatch: async () => null,
      otherPotWallets: async () => [],
      exclusionSets: async () => ({ all: new Set(), totalCount: 0 }),
      traderCandidates: async () => opts.traders.map(toCandidate),
      creatorCandidates: async () => opts.creators.map(toCandidate),
      stageWinners: async () => {},
      writeRewardAlert: async (_c: any, a: any) => { alerts.push(a); },
    });
  });

  const vaultAfter = BigInt(await vault.warzoneAirdropBalance());
  const dist = distAt(opts.distributor);
  const mainDist = opts.mainDistributor ? distAt(opts.mainDistributor) : null;
  const batches: Gen7AirdropWeekResult["batches"] = [];
  for (const b of fake.batches.values()) {
    const m = b.metadata;
    const rows = fake.ledger.filter((l) => l.metadata.batchId === b.id);
    const onChain = await dist.batches(m.contractBatchId);
    batches.push({
      program: m.program,
      contractBatchId: m.contractBatchId,
      expectedId: weeklyContractBatchId(opts.chainId, epochId, m.program, GEN7_POT),
      merkleRoot: m.merkleRoot,
      total: BigInt(m.merkleTotalAmount),
      winners: rows.map((r) => ({ wallet: ethers.getAddress(r.wallet_address), amount: BigInt(r.metadata.claimAmount), proof: r.metadata.merkleProof })),
      onChain: { totalFunded: BigInt(onChain.totalFunded), exists: Boolean(onChain.exists), claimDeadline: BigInt(onChain.claimDeadline) },
      mainHasIt: mainDist ? Boolean((await mainDist.batches(m.contractBatchId)).exists) : false,
      status: b.status,
    });
  }
  return {
    epochId, vaultBefore, vaultAfter, distributionBps, batches, fundRequests, fundTxs, alerts,
    funded: batches.reduce((s, b) => s + b.onChain.totalFunded, 0n),
    main: { before: mainBefore, after: await readMain() },
  };
}

/** A winner claims from the gen-7 distributor; returns the native received (gas excluded) and the main pot's answer. */
export async function claimGen7Win(opts: { distributor: string; mainDistributor: string | null; batchId: string; winner: { wallet: string; amount: bigint; proof: string[] }; signer: any }) {
  const dist = new ethers.Contract(opts.distributor, DISTRIBUTOR_ABI, opts.signer);
  let mainRefusal: string | null = null;
  if (opts.mainDistributor) {
    try {
      await new ethers.Contract(opts.mainDistributor, ["function claim(bytes32,uint256,bytes32[])", "error BatchMissing(bytes32)"], opts.signer).claim.staticCall(opts.batchId, opts.winner.amount, opts.winner.proof);
      mainRefusal = "NO_REVERT";
    } catch (e: any) {
      mainRefusal = e?.revert?.name || String(e?.shortMessage || e?.message || e).split("\n")[0];
    }
  }
  const before = await ethers.provider.getBalance(opts.winner.wallet);
  const rc = await (await dist.claim(opts.batchId, opts.winner.amount, opts.winner.proof)).wait();
  const after = await ethers.provider.getBalance(opts.winner.wallet);
  const gas = BigInt(rc.gasUsed) * BigInt(rc.gasPrice ?? 0n);
  return { received: after - before + gas, gas: rc.gasUsed, tx: rc.hash, claimed: await dist.hasClaimed(opts.batchId, opts.winner.wallet), mainRefusal };
}

type CheckFn = (name: string, pass: boolean, proof: Record<string, unknown>) => void;

/**
 * The gen-7 pot's acceptance after its wiring batch ran, shared by the two mainnet-fork rehearsals and the two
 * testnet lifecycle scripts:
 *   1. wiring read back + the runner's runway check as it will run on the first authorized Monday: 12 weeks
 *   2. one weekly draw through potRun.runPot funded from the gen-7 vault (the rehearsal's trades filled it) by the
 *      vault's airdrop operator (impersonated on a fork); ids = the runner's gen-7 ids; the main pot untouched
 *   3. a winner claims from the gen-7 distributor (the main distributor does not know the batch)
 * On a fork time is warped to the first authorized Monday + 15 min (the runner's slot). On a real testnet (no warp)
 * the admin authorizes the week that just ended with the runner's id (testnet only: the deployer is the owner there).
 */
export async function rehearseGen7AirdropPot(opts: {
  chainId: number;
  vault: string;
  setup: Gen7AirdropSetup;
  admin: string;
  traders: any[];
  creators: any[];
  nativeUsd: number;
  check: CheckFn;
  fork: boolean;
  testnetAdminSigner?: any;
  symbol: string;
}) {
  const { chainId, vault, setup, check } = opts;
  const nowSec = Number((await ethers.provider.getBlock("latest"))!.timestamp);
  const pot = await readGen7AirdropPot({ chainId, vault, setup, admin: opts.admin });
  const firstEnd = await firstAuthorizedGen7WeekEnd(chainId, setup.distributor, nowSec);
  check(`gen-7 airdrop pot wired by the admin batch: community vault -> its own airdrop distributor, airdrop operator = the main pot's (${setup.operatorSource}), distributor batchOperator = the gen-7 community vault, owner = admin`, pot.wired && firstEnd !== null, { ...pot, distributor: setup.distributor, cap: setup.cap, capSource: setup.capSource, firstAuthorizedWeekEnd: firstEnd ? new Date(firstEnd * 1000).toISOString() : null });
  const runAt = firstEnd! + 900;
  const pots = [{ pot: GEN7_POT, distributorAddress: setup.distributor }, ...(setup.mainDistributor ? [{ pot: "main", distributorAddress: setup.mainDistributor }] : [])];
  const runway = (await runnerRunway({ chainId, pots, nowSec: runAt })) as any[];
  const g = runway.find((r) => r.pot === GEN7_POT);
  const m = runway.find((r) => r.pot === "main");
  check("runner runway check (authorizationHorizon.mjs) on the first authorized Monday: the gen-7 pot has 12 weeks pre-authorized, verdict ok", g?.runway?.coveredWeeks === GEN7_AIRDROP_WEEKS && g?.verdict?.level === "ok", { gen7: { coveredWeeks: g?.runway?.coveredWeeks, from: g?.runway?.currentEpochId, through: g?.runway?.lastCoveredEpochId, verdict: g?.verdict?.level }, main: m ? { coveredWeeks: m.runway?.coveredWeeks, verdict: m.verdict?.level, error: m.error } : null });

  // Into the draw window.
  if (opts.fork) {
    const now = Number((await ethers.provider.getBlock("latest"))!.timestamp);
    if (runAt > now) {
      await network.provider.send("evm_increaseTime", [runAt - now]);
      await network.provider.send("evm_mine", []);
    }
  } else if (Number((await ethers.provider.getBlock("latest"))!.timestamp) < firstEnd!) {
    if (!opts.testnetAdminSigner || chainId === 56 || chainId === 4663) throw new Error("no warp on a live chain: the gen-7 draw waits for its first authorized Monday");
    const { weeklyContractBatchId } = await esm("frontend/scripts/weekly-airdrop/materialize.mjs");
    const now = Number((await ethers.provider.getBlock("latest"))!.timestamp);
    const end = utcEpochEnd(now);
    const d = new ethers.Contract(setup.distributor, DISTRIBUTOR_ABI, opts.testnetAdminSigner);
    for (const p of AIRDROP_PROGRAMS) {
      const id = weeklyContractBatchId(chainId, epochIdForEnd(end), p, GEN7_POT);
      const a = await d.batchAuthorization(id);
      if (!a.authorized && !a.consumed) await (await d.authorizeBatch(id, setup.cap, end, Math.max(end + 6 * DAY, now + 3600))).wait();
    }
    console.log(`[gen7-airdrop] testnet: the admin authorized the week ending ${new Date(end * 1000).toISOString()} (runner ids) so the draw runs now`);
  }

  const operator = ethers.getAddress(setup.operator);
  let fundAs: any;
  if (opts.fork) {
    await network.provider.send("hardhat_impersonateAccount", [operator]);
    await network.provider.send("hardhat_setBalance", [operator, ethers.toQuantity(ethers.parseEther("1"))]);
    fundAs = await ethers.getSigner(operator);
  } else {
    fundAs = opts.testnetAdminSigner; // testnet: the admin may fund (onlyAdminOrAirdropOperator)
  }
  const signers = new Map<string, any>([...opts.traders, ...opts.creators].map((w) => [ethers.getAddress(w.address), w]));
  let week: Gen7AirdropWeekResult;
  try {
    week = await runGen7AirdropWeek({ chainId, vault, distributor: setup.distributor, mainVault: setup.mainVault, mainDistributor: setup.mainDistributor, traders: opts.traders.map((w) => w.address), creators: opts.creators.map((w) => w.address), fundAs, nativeUsd: opts.nativeUsd });
  } finally {
    if (opts.fork) await network.provider.send("hardhat_stopImpersonatingAccount", [operator]);
  }
  const pool = (week.vaultBefore * BigInt(week.distributionBps)) / 10_000n;
  const fmt = (v: bigint) => `${ethers.formatEther(v)} ${opts.symbol}`;
  check(`weekly gen-7 draw through the runner (potRun.runPot -> materialize -> chain.mjs ensureOnChainBatch): trader + creator batches funded from the gen-7 vault by its airdrop operator, ids = weeklyContractBatchId(.., "gen7"), funded = ${week.distributionBps / 100}% of the vault, claim-open`,
    week.batches.length === 2 && week.batches.every((b) => b.contractBatchId === b.expectedId && b.onChain.exists && b.onChain.totalFunded === b.total && b.status === "claim_open" && !b.mainHasIt && b.winners.length > 0) &&
      week.funded === pool && week.vaultBefore - week.vaultAfter === week.funded && week.fundTxs.length === 2 && week.fundRequests.every((r) => same(r.targetContract, vault)) && week.alerts.length === 0,
    { epochId: week.epochId, vaultBefore: fmt(week.vaultBefore), funded: fmt(week.funded), vaultAfter: fmt(week.vaultAfter), fundedBy: fundAs.address ?? (await fundAs.getAddress()), batches: week.batches.map((b) => ({ program: b.program, id: b.contractBatchId, total: fmt(b.total), winners: b.winners.map((w) => `${w.wallet}=${fmt(w.amount)}`) })), fundTxs: week.fundTxs, alerts: week.alerts });

  const trader = week.batches.find((b) => b.program === "airdrop_trader")!;
  const winner = trader.winners[0];
  const claim = await claimGen7Win({ distributor: setup.distributor, mainDistributor: setup.mainDistributor, batchId: trader.contractBatchId, winner, signer: signers.get(winner.wallet) });
  const mainSame = week.main.before.vault === week.main.after.vault && week.main.before.distBalance === week.main.after.distBalance && week.main.before.outstanding === week.main.after.outstanding;
  check("a gen-7 winner claims from the gen-7 distributor (exact amount, by balance delta); the main distributor does not know the batch; the main pot (vault balance, distributor balance, outstanding) untouched",
    claim.received === winner.amount && claim.claimed && (setup.mainDistributor ? claim.mainRefusal !== "NO_REVERT" : true) && mainSame,
    { winner: winner.wallet, amount: fmt(winner.amount), received: fmt(claim.received), tx: claim.tx, mainDistributorClaim: claim.mainRefusal, main: { before: { vault: fmt(week.main.before.vault), distributor: fmt(week.main.before.distBalance), outstanding: fmt(week.main.before.outstanding) }, after: { vault: fmt(week.main.after.vault), distributor: fmt(week.main.after.distBalance), outstanding: fmt(week.main.after.outstanding) } } });
  return { epochId: week.epochId, vaultBefore: week.vaultBefore, funded: week.funded, batches: week.batches, claim, runway: { gen7: g?.runway, main: m?.runway } };
}
