export type HelpCategoryId =
  | "popular"
  | "wallets"
  | "create"
  | "trading"
  | "rewards"
  | "community"
  | "recruiters"
  | "safety";

export type HelpArticle = {
  id: string;
  title: string;
  body: string;
  categories: HelpCategoryId[];
  keywords: string[];
  popular?: boolean;
};

export const HELP_CATEGORIES: { id: HelpCategoryId; label: string }[] = [
  { id: "popular", label: "Popular" },
  { id: "wallets", label: "Wallets" },
  { id: "create", label: "Create & Launch" },
  { id: "trading", label: "Trading" },
  { id: "rewards", label: "Rewards" },
  { id: "community", label: "Community" },
  { id: "recruiters", label: "Recruiters & Squads" },
  { id: "safety", label: "Safety" },
];

export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: "what-is-memewarzone",
    title: "What is MemeWarzone?",
    body: "MemeWarzone is a multichain memecoin launchpad with a social feed. Creators prepare, launch and promote coins. Traders find and trade them before and after graduation, and coins can meet in battles and leagues.",
    categories: ["community"],
    keywords: ["memewarzone", "what is", "launchpad", "about"],
  },
  {
    id: "which-chains",
    title: "Which chains does MemeWarzone support?",
    body: "BNB Chain, Solana and Robinhood Chain. Each coin lives on one chain. Balances, coins and rewards are shown for the chain you have selected. Launching, trading, battles, imports and reward claims work on all three. Pick the chain at the top of the page.",
    categories: ["wallets", "create"],
    keywords: ["bnb", "solana", "chain", "network", "multichain"],
  },
  {
    id: "need-account",
    title: "Do I need an account?",
    body: "No. Your connected wallet is your identity. One wallet has one profile with a picture, name, @username and bio, and it shows the same on every chain.",
    categories: ["wallets", "community"],
    keywords: ["account", "signup", "login", "profile", "identity"],
  },
  {
    id: "browse-without-wallet",
    title: "Can I browse without connecting a wallet?",
    body: "Yes, for public pages. Trading, following, launching, posting and claiming need a connected wallet.",
    categories: ["wallets"],
    keywords: ["browse", "guest", "connect", "without wallet"],
  },
  {
    id: "wallets",
    title: "Which wallets can I use?",
    body: "BNB Chain: MetaMask, Rabby, Coinbase Wallet, Trust Wallet, OKX and other browser wallets. Solana: Phantom, Solflare and Backpack.",
    categories: ["wallets"],
    keywords: ["wallet", "metamask", "rabby", "phantom", "solflare", "backpack", "okx", "trust", "coinbase", "connect"],
    popular: true,
  },
  {
    id: "both-wallets",
    title: "Can I connect both a BNB wallet and a Solana wallet?",
    body: "Yes, from the same wallet selector. Features and balances stay on their own chain.",
    categories: ["wallets"],
    keywords: ["both wallets", "evm and solana", "two wallets"],
  },
  {
    id: "switch-networks",
    title: "Why am I being asked to switch networks?",
    body: "The action you started is on a different network than the one selected in your wallet. Switch in your wallet, or use the Switch network button in Command Center > Settings.",
    categories: ["wallets"],
    keywords: ["switch network", "wrong network", "chain mismatch"],
  },
  {
    id: "solana-wallet-bnb-data",
    title: "Does connecting a Solana wallet change BNB campaign data?",
    body: "No. Campaign data belongs to the campaign's chain, not to whichever wallet you connected last.",
    categories: ["wallets"],
    keywords: ["sol wallet", "bnb data", "cross chain", "wrong chain"],
  },
  {
    id: "balances-combined",
    title: "Are my BNB and SOL balances combined?",
    body: "No. Native balances and rewards stay separate per chain.",
    categories: ["wallets", "rewards"],
    keywords: ["balance", "bnb sol combined", "separate balances"],
  },
  {
    id: "create-token",
    title: "How do I create a token?",
    body: "Open Create. Fill in name, image, ticker, description, socials and graduation settings, then save a draft or deploy after you confirm in your wallet.",
    categories: ["create"],
    keywords: ["create", "launch", "deploy", "new token", "make a coin"],
    popular: true,
  },
  {
    id: "draft-vs-deploy",
    title: "What is the difference between Draft Mode and Direct Deploy?",
    body: "Draft Mode opens a Prepare Mode page without deploying a token. Direct Deploy creates the live on-chain campaign right after you confirm.",
    categories: ["create"],
    keywords: ["draft", "direct deploy", "difference", "prepare vs create"],
  },
  {
    id: "draft-gas",
    title: "Does creating a draft cost gas?",
    body: "No. A draft only needs a wallet signature. You pay gas when you deploy or schedule the live campaign.",
    categories: ["create"],
    keywords: ["draft gas", "free draft", "no gas"],
  },
  {
    id: "ticker",
    title: "Can someone else use my ticker?",
    body: "Create checks if a ticker is available. The final ticker depends on reservation and on whether the campaign is deployed.",
    categories: ["create"],
    keywords: ["ticker", "symbol", "taken", "reserved"],
  },
  {
    id: "launch-blocked",
    title: "Why can't I launch another token?",
    body: "Creator safety can block a launch because of a cooldown, a limit on live tokens, or eligibility rules. The Create screen shows which restriction applies.",
    categories: ["create", "safety"],
    keywords: ["cannot create", "can't create", "blocked", "cooldown", "creator limit", "live token limit", "launch blocked", "deploy"],
  },
  {
    id: "robinhood-chain",
    title: "What can I do on Robinhood Chain?",
    body: "Everything you can do on the other chains. Launch a coin, trade it on the curve and after graduation, import a coin, join battles, leagues and the Major War League, and claim rewards. The chain's coin is ETH. When you launch, you can pair your coin with ETH or an approved stock token for after graduation. Imported Robinhood coins trade through Uniswap.",
    categories: ["wallets", "create", "trading"],
    keywords: ["robinhood", "robinhood chain", "eth", "stock token", "uniswap"],
  },
  {
    id: "launch-both-chains",
    title: "Can I launch on BNB Chain, Solana and Robinhood Chain?",
    body: "Yes. You pick the chain when you create. Each coin lives on one chain.",
    categories: ["create"],
    keywords: ["launch both", "solana create", "bnb create", "robinhood create"],
  },
  {
    id: "creator-initial-buy",
    title: "Can I make an initial creator buy when I deploy?",
    body: "Creator buys follow the launch safety rules for that campaign. The trade panel shows the restrictions.",
    categories: ["create", "trading", "safety"],
    keywords: ["creator buy", "initial buy", "dev buy"],
  },
  {
    id: "prepare-mode",
    title: "What is Prepare Mode?",
    body: "Prepare Mode lets you build and promote a project before the token is deployed. You can gather followers, add socials, talk with the community and launch later.",
    categories: ["create"],
    keywords: ["prepare", "draft page", "promotion", "prelaunch"],
  },
  {
    id: "follow-before-exists",
    title: "Can people follow a token before it exists?",
    body: "Yes. People can follow Prepare Mode campaigns.",
    categories: ["create", "community"],
    keywords: ["follow draft", "follow prepare"],
  },
  {
    id: "arm-notification",
    title: "What does Arm Notification do?",
    body: "Followers of a Prepare Mode project can arm a launch alert, so they are notified when it goes live.",
    categories: ["create", "community"],
    keywords: ["arm", "notification", "launch alert"],
  },
  {
    id: "edit-prepare",
    title: "Can I edit my Prepare Mode page?",
    body: "Yes. Open Command Center > My coins, tap the draft and press Edit Draft. You can change it until the launch settings are committed.",
    categories: ["create"],
    keywords: ["edit draft", "edit prepare"],
  },
  {
    id: "hide-draft",
    title: "Can I hide or archive a draft?",
    body: "Yes. Draft visibility and archiving are in the creator tools of the draft.",
    categories: ["create"],
    keywords: ["hide draft", "archive", "unpublish"],
  },
  {
    id: "prepare-comments",
    title: "Can people comment on Prepare Mode campaigns?",
    body: "Yes. Prepare Mode pages have comments, reactions and creator replies.",
    categories: ["create", "community"],
    keywords: ["prepare comments", "transmissions", "bunker"],
  },
  {
    id: "share-prepare",
    title: "Can I share my Prepare Mode page?",
    body: "Yes. Share the page directly, including to X. MemeWarzone makes a share card for it.",
    categories: ["create"],
    keywords: ["share", "share card", "twitter", "x"],
  },
  {
    id: "schedule-launch",
    title: "Can I schedule my token launch?",
    body: "Yes. A prepared campaign can launch now or at a time you choose.",
    categories: ["create"],
    keywords: ["schedule", "timed launch", "countdown"],
  },
  {
    id: "what-happens-schedule",
    title: "What happens when I schedule a launch?",
    body: "You choose the launch settings and time and complete the deployment. Trading stays closed until that time.",
    categories: ["create"],
    keywords: ["scheduled launch", "trading closed"],
  },
  {
    id: "press-launch-again",
    title: "Do I need to come back and press Launch again?",
    body: "No. A timed launch opens by itself at the scheduled time.",
    categories: ["create"],
    keywords: ["auto launch", "push live", "come back"],
  },
  {
    id: "change-launch-time",
    title: "Can I change the launch time after deploy?",
    body: "No. Once the launch settings are on-chain, they cannot be changed.",
    categories: ["create"],
    keywords: ["change time", "reschedule", "immutable"],
  },
  {
    id: "launch-timezone",
    title: "Which timezone does the launch page use?",
    body: "The scheduler shows the launch time in your local timezone.",
    categories: ["create"],
    keywords: ["timezone", "utc", "local time"],
  },
  {
    id: "import-coin",
    title: "Can I bring a coin that launched somewhere else?",
    body: "Yes. Use Import memecoin in the menu, or Import memecoin in Command Center > My coins. An imported coin gets a page on MemeWarzone, shows up in search and can join battles. It appears in My coins with an Imported label and its ownership status.",
    categories: ["create"],
    keywords: ["import", "imported coin", "bring my coin", "pump.fun", "existing token"],
  },
  {
    id: "claim-memecoin",
    title: "How do I prove I own an imported coin?",
    body: "On the imported coin's page, open Claim memecoin. Verify with the project X account attached to the token, or with the project owner wallet (on Solana the project authority wallet). If neither works, request a manual review and give an X account where the team can reach you. Until then the coin shows Ownership pending.",
    categories: ["create", "safety"],
    keywords: ["claim memecoin", "verify ownership", "owner verified", "manual review", "imported"],
  },
  {
    id: "buy-sell",
    title: "How do I buy or sell?",
    body: "Open the coin page and use the trade panel. Coins on the bonding curve trade directly on MemeWarzone. Graduated coins trade through their DEX pool, still from the same page.",
    categories: ["trading"],
    keywords: ["buy", "sell", "trade", "swap"],
    popular: true,
  },
  {
    id: "quote-before-trade",
    title: "Do I see a quote before trading?",
    body: "Yes. The trade panel shows the expected output and the trade details before you sign.",
    categories: ["trading"],
    keywords: ["quote", "preview", "expected output"],
  },
  {
    id: "slippage",
    title: "What is slippage?",
    body: "Slippage is how much price movement you accept between the quote and the moment your trade goes through.",
    categories: ["trading"],
    keywords: ["slippage", "price impact"],
  },
  {
    id: "trade-failed",
    title: "Why did my trade fail?",
    body: "Common causes: not enough balance, slippage, trading restrictions on the campaign, creator buy rules, the wallet on the wrong network, or a paused market. The trade panel shows the actual error.",
    categories: ["trading"],
    keywords: ["trade failed", "transaction failed", "revert", "stuck"],
  },
  {
    id: "creators-trade-own",
    title: "Can creators trade their own coin?",
    body: "Creator trading can have buy locks and buy caps. The trade panel shows them.",
    categories: ["trading", "safety"],
    keywords: ["creator trade", "dev sell", "buy lock"],
  },
  {
    id: "war-trade-room",
    title: "What is the War Trade Room?",
    body: "The War Trade Room is the market screen. You can find, compare and trade campaigns from one place.",
    categories: ["trading"],
    keywords: ["war room", "war trade room", "terminal"],
  },
  {
    id: "trade-without-details",
    title: "Can I trade without opening the coin page?",
    body: "Yes. Expand a campaign row in the War Trade Room and trade there.",
    categories: ["trading"],
    keywords: ["trade from war room", "expand row"],
  },
  {
    id: "war-room-search",
    title: "What can I search for in the War Trade Room?",
    body: "Coin name, ticker, creator, token address and campaign address.",
    categories: ["trading"],
    keywords: ["search war room", "find token"],
  },
  {
    id: "search",
    title: "What can I find with search?",
    body: "Coins launched or imported on MemeWarzone by name, ticker or address, people by display name or @username, and any wallet by its address. Coins are searched on the chain you have selected. People are found on every chain.",
    categories: ["community", "trading"],
    keywords: ["search", "find", "find coin", "find user", "username search", "wallet search"],
  },
  {
    id: "war-room-both-chains",
    title: "Can I see projects from every chain in the War Trade Room?",
    body: "Yes. The War Trade Room shows the projects of the chain you have selected.",
    categories: ["trading"],
    keywords: ["war room solana", "war room bnb", "war room robinhood"],
  },
  {
    id: "war-room-prepare",
    title: "Does the War Trade Room include Prepare Mode projects?",
    body: "Yes. Draft and upcoming campaigns can appear there.",
    categories: ["trading", "create"],
    keywords: ["war room drafts", "upcoming"],
  },
  {
    id: "graduation",
    title: "What happens when a token graduates?",
    body: "Graduation moves the coin from the bonding curve into a DEX pool. On BNB Chain it moves to Topaz. On Solana it moves to Meteora, and you do not press a Graduate button. The coin page, chart and trade panel stay on MemeWarzone.",
    categories: ["trading"],
    keywords: ["graduate", "graduation", "dex", "bonding complete", "100%"],
    popular: true,
  },
  {
    id: "leave-after-grad",
    title: "Do I have to leave MemeWarzone after graduation?",
    body: "No. Graduation changes where the liquidity sits, not the product. You keep the same coin page, chart and trade panel.",
    categories: ["trading"],
    keywords: ["leave", "after graduation", "still trade here"],
  },
  {
    id: "bnb-after-grad",
    title: "Where do BNB tokens trade after graduation?",
    body: "Graduated BNB Chain coins trade through their Topaz pool, from the MemeWarzone coin page.",
    categories: ["trading"],
    keywords: ["topaz", "bnb dex", "graduated bnb"],
  },
  {
    id: "solana-after-grad",
    title: "Where do Solana tokens trade after graduation?",
    body: "Once a Solana coin has graduated on-chain, trading uses its Meteora pool inside MemeWarzone. A full bar alone is not graduation. Until the move to Meteora is confirmed, the coin is still bonding or waiting for its pool.",
    categories: ["trading"],
    keywords: ["meteora", "solana dex", "graduated sol"],
  },
  {
    id: "chart-reset",
    title: "Does my chart reset at graduation?",
    body: "No. The chart continues from the bonding curve into DEX trading.",
    categories: ["trading"],
    keywords: ["chart reset", "history", "candles"],
  },
  {
    id: "external-dex-trades",
    title: "Do external DEX trades appear on MemeWarzone?",
    body: "Yes. After graduation, the market history includes DEX trades, not only trades made on MemeWarzone.",
    categories: ["trading"],
    keywords: ["external trades", "dex prints"],
  },
  {
    id: "upvotes",
    title: "What are UpVotes?",
    body: "UpVotes are paid discovery. They raise a campaign's visibility and are not a token purchase. One UpVote costs $3, paid in the chain's own coin (BNB or SOL).",
    categories: ["trading"],
    keywords: ["upvote", "vote", "boost", "crowd favorite", "3 dollar", "$3"],
  },
  {
    id: "upvote-not-buy",
    title: "Does buying an UpVote buy the token?",
    body: "No. An UpVote promotes the campaign. It does not buy the token.",
    categories: ["trading"],
    keywords: ["upvote buy token"],
  },
  {
    id: "upvote-rankings",
    title: "Do UpVotes influence rankings?",
    body: "Yes. They count toward discovery and the Crowd Favorite competition.",
    categories: ["trading", "rewards"],
    keywords: ["upvote ranking", "crowd favorite"],
  },
  {
    id: "follow-what",
    title: "What can I follow?",
    body: "People, live coins and Prepare Mode campaigns.",
    categories: ["community"],
    keywords: ["follow", "following"],
  },
  {
    id: "where-following",
    title: "Where can I see my followers?",
    body: "Your public profile shows how many followers you have and how many accounts you follow.",
    categories: ["community"],
    keywords: ["my following", "followers"],
  },
  {
    id: "sign-every-message",
    title: "Do I have to sign every post, rocket or chat message?",
    body: "No. Your first social action asks for one wallet signature. It covers posts, replies, reposts, quotes, rockets, comments, War Room chat, reports, hides and blocks for 30 days in that browser. Changes tied to your wallet, like your profile, username or settings, ask for their own signature. Signatures are free.",
    categories: ["community", "wallets"],
    keywords: ["sign every message", "session", "signature", "sign again", "30 days", "why sign"],
    popular: true,
  },
  {
    id: "post-images",
    title: "How many images can I add to a post?",
    body: "Up to 4 images per post or creator update.",
    categories: ["community"],
    keywords: ["image", "images", "photo", "picture", "upload", "post"],
  },
  {
    id: "delete-post",
    title: "Can I delete my own post?",
    body: "Yes. Open the … menu on your post or reply and choose Delete. You are asked to confirm first.",
    categories: ["community"],
    keywords: ["delete", "remove post", "delete reply", "undo post"],
  },
  {
    id: "report-hide-block",
    title: "How do I report, hide or block?",
    body: "Open the … menu on a post, comment or profile. Report sends it to our team. Hide removes that one post or comment for you only. Block hides all posts and comments from that account for you; their coin pages and trading are not affected. Unblock in Command Center > Settings > Blocked accounts.",
    categories: ["community", "safety"],
    keywords: ["report", "hide", "block", "unblock", "mute", "spam"],
  },
  {
    id: "views",
    title: "How are views counted?",
    body: "Each post counts one view per wallet that has signed in for social actions. Visitors without that signature count once per post per IP address.",
    categories: ["community"],
    keywords: ["views", "view count", "impressions", "unique views"],
  },
  {
    id: "creator-updates",
    title: "What are creator updates?",
    body: "The owner of a coin can post updates on the coin page, with up to 4 images. You post as the coin, and updates also appear in the home feed unless you untick that. People can rocket, repost, quote and reply to them like any post.",
    categories: ["community", "create"],
    keywords: ["creator update", "coin update", "post as coin", "holders"],
  },
  {
    id: "notifications",
    title: "What notifications can I receive?",
    body: "Battle challenges, replies, reposts and @mentions, rewards ready to claim, and events for coins you created such as drafts, launch and graduation. The bell shows the latest. View all opens Command Center > Notifications.",
    categories: ["community"],
    keywords: ["notifications", "alerts", "bell"],
  },
  {
    id: "notification-settings",
    title: "Can I turn notifications off or get them by email?",
    body: "Yes. In Command Center > Settings > Notification settings, each category has a Bell switch and an Email switch. Email needs a verified address: add it under Arena challenge email and open the link we send you. Press Save notification settings and sign to apply.",
    categories: ["community"],
    keywords: ["notification settings", "email", "turn off", "mute notifications", "email notifications"],
  },
  {
    id: "mark-read",
    title: "Can I mark notifications as read?",
    body: "Yes. Opening a notification marks it read. Mark all read on the Notifications tab marks them all.",
    categories: ["community"],
    keywords: ["mark read", "mark all"],
  },
  {
    id: "token-chat",
    title: "Does every token have a chat?",
    body: "Campaigns can have their own live War Room chat on the coin page.",
    categories: ["community"],
    keywords: ["chat", "war room chat", "comments"],
  },
  {
    id: "read-chat-no-wallet",
    title: "Do I need a wallet just to read chat?",
    body: "No. You can read without connecting. Posting needs a connected wallet.",
    categories: ["community"],
    keywords: ["read only chat"],
  },
  {
    id: "comments-vs-war-room",
    title: "What is the difference between comments and War Room chat?",
    body: "Comments stay on the campaign page. The War Room is the live chat for the campaign.",
    categories: ["community"],
    keywords: ["comments vs chat", "transmissions"],
  },
  {
    id: "public-profile",
    title: "What can other users see on my profile?",
    body: "Your picture, banner, name, @username, bio and links, your wallet, follower counts, your posts, coins you created and coins you hold. Settings > Portfolio display can hide native coins, stablecoins and small holdings from the list.",
    categories: ["community"],
    keywords: ["public profile", "what can they see"],
  },
  {
    id: "follow-user",
    title: "Can I follow another user?",
    body: "Yes, with the Follow button on their public profile.",
    categories: ["community"],
    keywords: ["follow user"],
  },
  {
    id: "edit-profile",
    title: "How do I edit my profile?",
    body: "Open Command Center > Edit profile, or press the grey Edit button on your own profile. You can change your picture, banner, display name, @username, bio (280 characters), website, X and Telegram. Saving asks for one signature and costs no fee. The same profile shows on every chain.",
    categories: ["community"],
    keywords: ["edit profile", "username", "avatar", "bio", "banner", "picture"],
    popular: true,
  },
  {
    id: "username",
    title: "How do usernames work?",
    body: "Your @username is how people tag you in posts. It has 3 to 20 characters (letters, numbers and underscores) and must be unique. You can change it once every 30 days. Set it in Command Center > Edit profile. People can find you by @username in search.",
    categories: ["community"],
    keywords: ["username", "handle", "@", "tag", "mention", "change username"],
  },
  {
    id: "ranks",
    title: "What are MemeWarzone ranks?",
    body: "A military-style path: Recruit, Soldier, Corporal, Captain, General. You can share a promotion when you rank up.",
    categories: ["community"],
    keywords: ["rank", "recruit", "soldier", "captain", "general"],
  },
  {
    id: "command-center",
    title: "What is the Command Center?",
    body: "Your private dashboard. Tabs: Overview, My coins, Battles (when you own a coin that can battle), Recruiter, Squad (when you are in one), Airdrops, Rewards and claims, Support and safety, Notifications, Edit profile and Settings. On a phone, swipe the tab row or tap the arrows.",
    categories: ["community"],
    keywords: ["command center", "dashboard", "tabs"],
  },
  {
    id: "portfolio",
    title: "What does the Overview tab show?",
    body: "Your native balance, how many coins you hold, total value, top holding, MemeWarzone coins and wallet age, plus a list of your top holdings with USD values. Coins launched or imported on MemeWarzone open their coin page.",
    categories: ["community", "wallets"],
    keywords: ["portfolio", "overview", "holdings", "total value", "balance"],
  },
  {
    id: "portfolio-display",
    title: "Can I hide stablecoins or dust from my holdings?",
    body: "Yes. Command Center > Settings > Portfolio display has two switches: Hide native coins and stablecoins, and Hide holdings under $1. They apply to Command Center and your public profile. Total value still counts every holding.",
    categories: ["community", "wallets"],
    keywords: ["hide", "stablecoins", "dust", "small holdings", "portfolio display", "usdc", "usdt"],
  },
  {
    id: "my-coins",
    title: "Where do I find tokens I created or my drafts?",
    body: "Command Center > My coins lists the coins you launched, your drafts and the coins you imported.",
    categories: ["create", "community"],
    keywords: ["my coins", "my drafts", "created tokens"],
  },
  {
    id: "lp-fees",
    title: "How do I claim creator LP fees?",
    body: "After your coin graduates, open Command Center > My coins and tap the coin. The row shows the unclaimed LP fees and a Claim LP fees button; 80% goes to you. If the pool is not ready or nothing is waiting, the row says so. Trading fees from the bonding curve are claimed under Creator fees in Rewards and claims.",
    categories: ["rewards", "create"],
    keywords: ["lp fees", "harvest", "creator fees", "pool not ready"],
  },
  {
    id: "leagues",
    title: "What are MemeWarzone Leagues?",
    body: "Recurring competitions: Perfect Run, Fastest Finish, Biggest Hit, Top Earner, Crowd Favorite and Recruiter League. Some run weekly and monthly, others monthly only. League pages show prize pools and previous periods.",
    categories: ["rewards"],
    keywords: ["league", "competition", "prize pool"],
  },
  {
    id: "crowd-favorite",
    title: "What determines Crowd Favorite?",
    body: "Confirmed unique UpVotes.",
    categories: ["rewards", "trading"],
    keywords: ["crowd favorite"],
  },
  {
    id: "recruiter",
    title: "What is a MemeWarzone Recruiter?",
    body: "Recruiters bring creators, traders and communities in and build a Squad. Anyone can apply from Command Center > Recruiter. Signup works with BNB Chain or Solana wallets.",
    categories: ["recruiters"],
    keywords: ["recruiter", "apply", "signup"],
  },
  {
    id: "recruiter-code",
    title: "What is a recruiter code?",
    body: "Each recruiter has a code and a shareable /r/CODE link. Recruiters can change the code in Command Center > Recruiter after signing in.",
    categories: ["recruiters"],
    keywords: ["recruiter code", "referral", "/r/"],
  },
  {
    id: "join-recruiter",
    title: "What happens when I join through a recruiter?",
    body: "Your wallet is linked to that recruiter's Squad under the attribution rules.",
    categories: ["recruiters"],
    keywords: ["join recruiter", "attribution"],
  },
  {
    id: "recruiter-bnb-sol",
    title: "Can recruiters earn both BNB and SOL?",
    body: "Yes. Recruiter earnings stay in each chain's own coin: BNB stays BNB, SOL stays SOL. Claim them in Command Center > Rewards and claims, in the Recruiter Rewards card, after signing once with your recruiter wallet. On Solana, small amounts add up until they reach the 0.005 SOL minimum.",
    categories: ["recruiters", "rewards"],
    keywords: ["recruiter sol", "recruiter bnb", "payout"],
  },
  {
    id: "squad",
    title: "What is a Squad?",
    body: "A Squad is the community around a recruiter. Wallets linked to that recruiter join it and, if eligible, share the Squad Pool.",
    categories: ["recruiters"],
    keywords: ["squad", "squad pool"],
  },
  {
    id: "squad-rank",
    title: "Where do I see my Squad?",
    body: "Command Center > Squad appears when you are in a squad. It shows the squad status, members, eligible members and the pending pool. Public squad standings are on the Squads page.",
    categories: ["recruiters"],
    keywords: ["squad rank", "estimated reward", "squad tab"],
  },
  {
    id: "squad-not-eligible",
    title: "Why am I not eligible for Squad rewards?",
    body: "Membership alone is not enough. Your own activity has to qualify, and fair-play rules apply. The Squad tab shows how many members are eligible.",
    categories: ["recruiters", "safety"],
    keywords: ["not eligible", "squad eligibility"],
  },
  {
    id: "airdrops",
    title: "What are Warzone Airdrops?",
    body: "Weekly rewards for eligible creators and traders. Command Center > Airdrops shows the current pool, the countdown to the Monday drop, whether your wallet is in this week's preview, and past winners. Wins can be claimed for 60 days; after that they go back into the pot.",
    categories: ["rewards"],
    keywords: ["airdrop", "warzone airdrop", "weekly"],
  },
  {
    id: "rewards",
    title: "Where can I see and claim my rewards?",
    body: "Command Center > Rewards and claims. It lists League rewards (Major War League prizes included), Airdrop, Squad and Recruiter rewards, battle wins and creator fees for the selected chain. Claims work on BNB Chain, Solana and Robinhood Chain. Connect the wallet that earned the reward.",
    categories: ["rewards"],
    keywords: ["claim", "rewards", "claim center", "solana claim", "mwl", "major war league"],
    popular: true,
  },
  {
    id: "reward-statuses",
    title: "What do Ready, Pending, Failed and Expired mean?",
    body: "Ready: you can claim now. Pending: a claim is already in progress. Failed: the last attempt did not finish, press Retry Claim. Expired: the claim window has closed. No rewards yet: nothing to claim on that row. A failed or cancelled claim never removes the reward.",
    categories: ["rewards"],
    keywords: ["pending", "claimable", "ready", "failed claim", "expired"],
  },
  {
    id: "claim-all",
    title: "What does Claim all ready do?",
    body: "When more than one reward is Ready, Claim all ready claims them one after another. Your wallet asks you to confirm each claim, so expect one signature per reward.",
    categories: ["rewards"],
    keywords: ["claim all", "claim everything", "batch claim", "multiple rewards"],
  },
  {
    id: "battle-prize",
    title: "How do I collect a battle prize?",
    body: "Battle and tournament wins have their own rows in Command Center > Rewards and claims. The wallet that owns the winning coin collects. The row says Waiting for on-chain result until the battle is settled, and Claimed once you have collected.",
    categories: ["rewards"],
    keywords: ["battle prize", "war pool", "battle win", "tournament prize"],
  },
  {
    id: "solana-claim-cost",
    title: "Why does a Solana claim cost a little SOL?",
    body: "Every Solana claim creates a receipt that needs a small deposit of about 0.0013 SOL. That is why Solana prizes have a 0.005 SOL minimum. Smaller amounts are not paid on their own; they roll over or add up.",
    categories: ["rewards", "wallets"],
    keywords: ["solana claim fee", "rent", "claim cost", "minimum payout", "0.005"],
  },
  {
    id: "crypticpump",
    title: "What is the CrypticPump button?",
    body: "Creators can send a BNB or Solana project to CrypticPump's listing from the coin page. After listing, the button can become a Listed badge. CrypticPump gets no control over the token.",
    categories: ["create"],
    keywords: ["crypticpump", "listing", "badge"],
  },
  {
    id: "help-or-abuse",
    title: "Where do I get help or report abuse?",
    body: "Search these help questions first. Wallet, trade, create and reward questions go to Discord support. Impersonation, stolen images, fake official profiles and phishing go to File Abuse Report in Command Center > Support and safety. Replies appear in My Abuse Reports.",
    categories: ["safety"],
    keywords: ["help", "support", "discord", "report abuse", "ticket"],
    popular: true,
  },
  {
    id: "what-is-abuse",
    title: "What should I use Report Abuse for?",
    body: "Someone impersonating you, using your images without permission, a fake project or profile pretending to be you, phishing with your identity, or similar identity abuse.",
    categories: ["safety"],
    keywords: ["impersonation", "stolen", "fake project", "phishing"],
  },
  {
    id: "failed-tx-not-abuse",
    title: "Should I report a failed transaction as abuse?",
    body: "No. Trading, wallet, reward and product problems belong in Discord support.",
    categories: ["safety", "trading"],
    keywords: ["failed transaction abuse", "not abuse"],
  },
  {
    id: "abuse-evidence",
    title: "Can I attach evidence to an Abuse Report?",
    body: "Yes. JPG, PNG, WEBP or PDF, up to 5 files of 10 MB each. You can add more later in the case conversation.",
    categories: ["safety"],
    keywords: ["evidence", "screenshot", "pdf"],
  },
  {
    id: "abuse-reply-email",
    title: "How will I know when Abuse replies? Can I email back?",
    body: "You get an email when there is a reply, and the reply appears in Command Center > Support and safety > My Abuse Reports. Do not answer the email. Reply inside the case.",
    categories: ["safety"],
    keywords: ["abuse email", "reply email", "case number"],
  },
  {
    id: "who-sees-abuse",
    title: "Who can see my Abuse Report?",
    body: "Only you and the abuse team. Regular Discord support cannot see Abuse Reports.",
    categories: ["safety"],
    keywords: ["who can see", "private", "abuse department"],
  },
];

export const DISCORD_SUPPORT_URL = "https://discord.gg/aXTkn3Asu";

export function searchHelpArticles(query: string, category: HelpCategoryId = "popular"): HelpArticle[] {
  const needle = String(query || "").trim().toLowerCase();
  if (needle) {
    return HELP_ARTICLES.filter((article) => {
      const haystack = [article.title, article.body, ...article.keywords].join(" ").toLowerCase();
      return haystack.includes(needle);
    });
  }
  if (category === "popular") return HELP_ARTICLES.filter((article) => article.popular);
  return HELP_ARTICLES.filter((article) => article.categories.includes(category));
}
